### PR TITLE
Fix S3 client config passing for image upload

### LINKED ISSUE #1572: imageUploadType use s3 with docker ,can't use
Install 2.2.0 with docker .
When imageUploadType set to s3 .
Upload image have error
> Error response received from instance metadata service codimd

I find a way can fix it 

* /lib/imageRouter/s3.js
```
const credentials = {
  accessKeyId: config.s3.accessKeyId,
  secretAccessKey: config.s3.secretAccessKey,
}

const s3 = new S3Client({
  credentials,
  region: config.s3.region
})

```
reference https://github.com/aws/aws-sdk-js-v3/issues/1396

### PR DESCRIPTION
**Pull request by jackycute**
Fix #1572 which not passing config to S3 client properly

ref issue: https://github.com/aws/aws-sdk-js-v3/issues/1396

Signed-off-by: Max Wu <jackymaxj@gmail.com>

### CODE REVIEW

**Review by a60814billy — APPROVED** [review]

**Comment by r10r** [comment]
Hi there, I'm facing the same issue as #1572. I noticed your fix doesn't make it into the latest release. 
Any plans when this bugfix is gonna released ?

**Comment by jackycute** [comment]
> Hi there, I'm facing the same issue as #1572. I noticed your fix doesn't make it into the latest release.
> Any plans when this bugfix is gonna released ?

Hi @r10r, it will be released in next version, hopefully can make it in the next month.

**Comment by r10r** [comment]
@jackycute  Thanks for the quick response! I'll look forward to the next release.

**Comment by r10r** [comment]
Btw. I'm facing another TLS connection issue, but I'll create an issue for that.

**Pull request merged**
