### PR TITLE
Add missing catch blocks for migration from 1.1.1 to 1.2.0

### PR DESCRIPTION
**Pull request by hcaloto**
I found some problems when upgrading from 1.1.1 to 1.2.0 and all of them were related to duplicated keys. In my case, these changes solved the issue.

Thanks to @SISheogorath since it is based on pull request #877

### CODE REVIEW

**Comment by SISheogorath** [comment]
Could you please fix the syntax errors for this PR before we merge it? https://travis-ci.org/hackmdio/codimd/jobs/401647961#L494-L596

**Comment by hcaloto** [comment]
@SISheogorath Sorry, I didn't wait for the test to be completed so I was not aware of the syntax errors. Now there is no conflicts

**Comment by SISheogorath** [comment]
All good, no problem :)

Can you also squash your commits? `git rebase -i master` and mark your second and third commit as `fixup`, please?

**Comment by hcaloto** [comment]
@SISheogorath Now all changes are in one commit, much more clean

**Comment by SISheogorath** [comment]
Thanks a lot!

**Comment by SISheogorath** [comment]
@hcaloto what `sequelize` version are you running? I just noticed that the error messages look different on the version we run on heroku

**Comment by hcaloto** [comment]
@SISheogorath We are using sequelize 3.33.0. If the error messages are different depending of sequelize, these errors should be fixed by other way. Maybe the `error` object has another key regardless of the version, like "error code" or something like that

**Pull request merged**
