### PR TITLE
Fix some webpack issues

### PR DESCRIPTION
**Pull request by SISheogorath**
We should use hashes for production builds. This prevents problems
during upgrades. At the same time, disable various optimizations and
features of webpack during development builds to speedup development
builds.

/cc @davidmehren

### CODE REVIEW

**Comment by SISheogorath** [comment]
Then let's undo the caching time change and merge this for now ^^

**Comment by davidmehren** [comment]
Okay, so while cleaning up the webpack config I stumbled upon https://github.com/webpack/webpack-dev-server/issues/377#issuecomment-241258405.

It seems that using hashes in the dev-config is a bad idea and we should only use them in production.

**Comment by SISheogorath** [comment]
Well, as far as I can say, we don't use `webpack-dev-server`. In our case it simply bloats the disk a bit.

The stated problem is related to the point that `webpack-dev-server` seems to cache the resulting files in memory without keeping track of where the files are originating from.

**Comment by SISheogorath** [comment]
Completely refactored this PR. Please recheck @davidmehren

**Comment by SISheogorath** [comment]
replaced by #1007

**Pull request closed without merging**
