### PR TITLE
Fix history page nav

### LINKED ISSUE #1778: History page display is misaligned
After updating to v2.4.2, the history page is misaligned.
This makes it impossible to press some buttons.
This is occurring in Chrome and Safari.

image

### PR DESCRIPTION
**Pull request by jackycute**
to avoid overlapping other buttons, affected by #1695

截圖 2023-06-05 下午3 58 25

fixes #1778, #1783

### CODE REVIEW

**Review by a60814billy — APPROVED** [review]
Looks good!

**Comment by slhck** [comment]
Thanks! Would you consider making a release, also given that the last one was done many months ago?

**Comment by jackycute** [comment]
> Thanks! Would you consider making a release, also given that the last one was done many months ago?

I will arrange a release this or next month.

**Comment by slhck** [comment]
What is currently blocking a release?

**Comment by jackycute** [comment]
> What is currently blocking a release?

To be honest, just don't have enough time at the moment.

**Comment by slhck** [comment]
Any update on a release? I would have hoped it should be as simple as calling a release script?

**Pull request merged**
