### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by cloudyu**

### CODE REVIEW

**Comment by ccoenen** [comment]
Hi! Would you like to elaborate on your changes? As far as I can see, one of the three commits is part of #1082 already. The "limited" change looks like it limits reading to the owner - which is not intended. Please refer to the [permissions table](https://demo.codimd.org/features#Permissions), only "private" is supposed to lock everyone else out.

**Comment by cloudyu** [comment]
The latter two commits are meant to implement my own desired functionality. Because the wrong branch was submitted. Please ignore them

**Comment by cloudyu** [comment]
The latter two commits are meant to implement my own desired functionality. because the wrong branch was submitted. Please ignore him

**Comment by ccoenen** [comment]
No problem :-) Thanks for clarifying.

**Pull request closed without merging**
