### PR TITLE
Release 2.4.2

### PR DESCRIPTION
**Pull request by a60814billy**
## Security Fixes
- #1685 **[Security Issue]** Upgrade flowchart.js to version 1.15.0
- #1690 **[Security Issue]** Upgrade mermaid to 8.10.2
- #1691 **[Security Issue]** Strip HTML tags for gist id to avoid stored XSS on showing error
- #1695 **[Security Issue]** Add CSRF token in export API to prevent security issue
- #1716 **[Security Issue]** Upgrade CodeMirror to 5.63.2

## Fixes

- #1605 Fix container syntax not parsed correctly
- #1679 Handle when request url has no valid referer
- #1683 Fix S3 client config passing for image upload
- #1706 Fix array access index may out of bound
- #1723 remove unused uglifyjs webpack plugin dependency

## Enhancements

- #1481 Set lang attributes via user locale
- #1580 Use include function instead of directives
- #1587 Extract more keyword for i18n translate
- #1680 Avoid append zero suffix on exporting user data
- #1684 Add TeX mhchem extensions for MathJax
- #1701 Support arm64 docker image
- #1724 Refactor Sequelize model import mechanism due to sequelize.import is deprecated
- #1741 Better german translation

## DX

- #1688 Support DevContainer for GitHub Codespaces and VSCode remote container
- #1694 Run CI with GitHub Actions

### CODE REVIEW

**Review by jackycute — APPROVED** [review]

**Review by jackycute — CHANGES_REQUESTED** [review]
I think this PR should be version 2.4.2 instead?

**Comment by productiveme** [comment]
Wondering if this will merge and release any time soon?

**Comment by inductor** [comment]
@a60814billy @jackycute What's the status of this PR?

**Review by jackycute — APPROVED** [review]
Thanks @a60814billy

**Pull request merged**
