### PR TITLE
Add some catch blocks for migrations.

### LINKED ISSUE #876: Upgrading a Docker alpine setup from 1.1.0 to 1.2.0 yields Internal Server Error
When upgrading from 1.1.0 to 1.2.0 we receive `Internal Server Error` on the frontend.
The service reports:

```
# docker-compose pull web && docker-compose stop web && docker-compose rm -f web && docker-compose up -d web
Pulling web (hackmdio/hackmd:alpine)...                                                                      
alpine: Pulling from hackmdio/hackmd                                           
Digest: sha256:73d3fedf33bd135fb4cc2abc5cbf704b58aab60131a78632eb557194a06a0e54
Status: Image is up to date for hackmdio/hackmd:alpine                                    
Stopping hackallmendeio_web_1 ... done                                                   
Going to remove hackallmendeio_web_1                                                           
Removing hackallmendeio_web_1 ... done                                                                                                                                                                                                                
hackallmendeio_postgres_1 is up-to-date                                                   
Creating hackallmendeio_web_1                                                              
# docker-compose logs -f web                                       
Attaching to hackallmendeio_web_1                                                                                           
web_1       | 2018/06/30 20:11:16 Waiting for: tcp://postgres:5432                                                      
web_1       | 2018/06/30 20:11:16 Connected to tcp://postgres:5432                                                                      
web_1       |                                                                                                  
web_1       | Sequelize [Node: 8.11.3, CLI: 2.8.0, ORM: 3.30.4]                                                                         
web_1       |                                                                                                
web_1       | Parsed url postgres://hackmd:*****@postgres:5432/hackmd                                      
web_1       | (node:28) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
web_1       | == 20150702001020-update-to-0_3_1: migrating =======                                                          
web_1       | { SequelizeDatabaseError: column "shortid" of relation "Notes" already exists    
web_1       |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)               
web_1       |     at Result.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
web_1       |     at emitOne (events.js:116:13)                                                
web_1       |     at Result.emit (events.js:211:7)                                        
web_1       |     at Result.Query.handleError (/hackmd/node_modules/pg/lib/query.js:163:8)     
web_1       |     at Client.<anonymous> (/hackmd/node_modules/pg/lib/client.js:188:26)    
web_1       |     at emitOne (events.js:116:13)           
web_1       |     at Connection.emit (events.js:211:7)                       
web_1       |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:133:12)
web_1       |     at emitOne (events.js:116:13)                                                
web_1       |     at Socket.emit (events.js:211:7)                                        
web_1       |     at addChunk (_stream_readable.js:263:12)                                                                  
web_1       |     at readableAddChunk (_stream_readable.js:250:11)
web_1       |     at Socket.Readable.push (_stream_readable.js:208:10)       
web_1       |     at TCP.onread (net.js:597:20)                                          
web_1       |   name: 'SequelizeDatabaseError',                                                
web_1       |   message: 'column "shortid" of relation "Notes" already exists',           
web_1       |   parent:                                                                                                     
web_1       |    { error: column "shortid" of relation "Notes" already exists
web_1       |     at Connection.parseE (/hackmd/node_modules/pg/lib/connection.js:567:11)
web_1       |     at Connection.parseMessage (/hackmd/node_modules/pg/lib/connection.js:391:17)
web_1       |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:129:22)     
web_1       |     at emitOne (events.js:116:13)                                           
web_1       |     at Socket.emit (events.js:211:7)
web_1       |     at addChunk (_stream_readable.js:263:12)    
web_1       |     at readableAddChunk (_stream_readable.js:250:11)                                                          
web_1       |     at Socket.Readable.push (_stream_readable.js:208:10)
web_1       |     at TCP.onread (net.js:597:20)                              
web_1       |      name: 'error',                                                                                           
web_1       |      length: 131,                                                                                         
web_1       |      severity: 'ERROR',                                                                                                   
web_1       |      code: '42701',                                                                                       
web_1       |      detail: undefined,                                                                                                                                                                                                                  
web_1       |      hint: undefined,                                                                                                                                                                                                                  
web_1       |      position: undefined,                                                                    
web_1       |      internalPosition: undefined,                                                                             
web_1       |      internalQuery: undefined,                                     
web_1       |      where: undefined,                                         
web_1       |      schema: undefined,                                                    
web_1       |      table: undefined,                                                           
web_1       |      column: undefined,                                                     
web_1       |      dataType: undefined,                                                                                     
web_1       |      constraint: undefined,                                                                               
web_1       |      file: 'tablecmds.c',                                                                                                                                                                                                                
web_1       |      line: '5110',                                                                                                                                                                                                                     
web_1       |      routine: 'check_for_column_name_collision',                                             
web_1       |      sql: 'ALTER TABLE "public"."Notes" ADD COLUMN "shortid" VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' },
web_1       |   original:                                                                                                   
web_1       |    { error: column "shortid" of relation "Notes" already exists                                           
web_1       |     at Connection.parseE (/hackmd/node_modules/pg/lib/connection.js:567:11)                                                                                                                                                              
web_1       |     at Connection.parseMessage (/hackmd/node_modules/pg/lib/connection.js:391:17)                                                                                                                                                      
web_1       |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:129:22)                 
web_1       |     at emitOne (events.js:116:13)                                
web_1       |     at Socket.emit (events.js:211:7)                               
web_1       |     at addChunk (_stream_readable.js:263:12)
web_1       |     at readableAddChunk (_stream_readable.js:250:11)
web_1       |     at Socket.Readable.push (_stream_readable.js:208:10)
web_1       |     at TCP.onread (net.js:597:20)
web_1       |      name: 'error',   
web_1       |      length: 131,      
web_1       |      severity: 'ERROR',  
web_1       |      code: '42701',        
web_1       |      detail: undefined,  
web_1       |      hint: undefined,
web_1       |      position: undefined,                       
web_1       |      internalPosition: undefined,                                                                             
web_1       |      internalQuery: undefined,                                                                            
web_1       |      where: undefined,                                                                                                                                                                                                                   
web_1       |      schema: undefined,                                                                                                                                                                                                                
web_1       |      table: undefined,                                                                       
web_1       |      column: undefined,                                          
web_1       |      dataType: undefined,                                          
web_1       |      constraint: undefined,
web_1       |      file: 'tablecmds.c',
web_1       |      line: '5110',
web_1       |      routine: 'check_for_column_name_collision',
web_1       |      sql: 'ALTER TABLE "public"."Notes" ADD COLUMN "shortid" VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' },
web_1       |   sql: 'ALTER TABLE "public"."Notes" ADD COLUMN "shortid" VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' }
web_1       | 2018-06-30T20:11:21.877Z - warn: Using legacy HMD prefix for environment variables. Please change your variables in future. For details see: https://github.com/hackmdio/codimd#environment-variables-will-overwrite-other-server-configs
web_1       | (node:1) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
web_1       | >> WARNING: PostgreSQL does not support TEXT with options. Plain `TEXT` will be used instead.
web_1       | >> Check: http://www.postgresql.org/docs/9.4/static/datatype.html
web_1       | 2018-06-30T20:11:23.053Z - info: HTTP Server listening at port 3000
```

### PR DESCRIPTION
**Pull request by SISheogorath**
(Hopefully) fixes #876

### CODE REVIEW

**Comment by almereyda** [comment]
I should be able to test this on our instance.

**Comment by almereyda** [comment]
This only adds new errors to be displayed with the known *Internal Server Error*:

```
web_1       | 2018-07-05T13:52:05.870Z - info: ::ffff:172.19.0.2 - - [05/Jul/2018:13:52:05 +0000] "GET / HTTP/1.1" 500 148 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36"
web_1       |
web_1       | 2018-07-05T13:52:06.125Z - error:  SequelizeDatabaseError: column "deleteToken" does not exist
web_1       |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
web_1       |     at Result.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
web_1       |     at emitOne (events.js:116:13)
web_1       |     at Result.emit (events.js:211:7)
web_1       |     at Result.Query.handleError (/hackmd/node_modules/pg/lib/query.js:163:8)
web_1       |     at Client.<anonymous> (/hackmd/node_modules/pg/lib/client.js:188:26)
web_1       |     at emitOne (events.js:116:13)
web_1       |     at Connection.emit (events.js:211:7)
web_1       |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:133:12)
web_1       |     at emitOne (events.js:116:13)
web_1       |     at Socket.emit (events.js:211:7)
web_1       |     at addChunk (_stream_readable.js:263:12)
web_1       |     at readableAddChunk (_stream_readable.js:250:11)
web_1       |     at Socket.Readable.push (_stream_readable.js:208:10)
web_1       |     at TCP.onread (net.js:597:20)
web_1       | SequelizeDatabaseError: column "deleteToken" does not exist
web_1       |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
web_1       |     at Result.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
web_1       |     at emitOne (events.js:116:13)
web_1       |     at Result.emit (events.js:211:7)
web_1       |     at Result.Query.handleError (/hackmd/node_modules/pg/lib/query.js:163:8)
web_1       |     at Client.<anonymous> (/hackmd/node_modules/pg/lib/client.js:188:26)
web_1       |     at emitOne (events.js:116:13)
web_1       |     at Connection.emit (events.js:211:7)
web_1       |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:133:12)
web_1       |     at emitOne (events.js:116:13)
web_1       |     at Socket.emit (events.js:211:7)
web_1       |     at addChunk (_stream_readable.js:263:12)
web_1       |     at readableAddChunk (_stream_readable.js:250:11)
web_1       |     at Socket.Readable.push (_stream_readable.js:208:10)
web_1       |     at TCP.onread (net.js:597:20)
```

or as a special variation of those above

```
web_1       | 2018-07-05T13:49:38.197Z - error:  SequelizeDatabaseError: column owner.deleteToken does not exist                                               
web_1       |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)       
web_1       |     at Result.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
web_1       |     at emitOne (events.js:116:13)                                                                                                                
web_1       |     at Result.emit (events.js:211:7)                                                           
web_1       |     at Result.Query.handleError (/hackmd/node_modules/pg/lib/query.js:163:8)                                                                     
web_1       |     at Client.<anonymous> (/hackmd/node_modules/pg/lib/client.js:188:26)                                  
web_1       |     at emitOne (events.js:116:13)                                                              
web_1       |     at Connection.emit (events.js:211:7)                                                                                                         web_1       |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:133:12)
web_1       |     at emitOne (events.js:116:13)                                                              
web_1       |     at Socket.emit (events.js:211:7)                                                           
web_1       |     at addChunk (_stream_readable.js:263:12)                                                   
web_1       |     at readableAddChunk (_stream_readable.js:250:11)                                                                                             
web_1       |     at Socket.Readable.push (_stream_readable.js:208:10)                                                  
web_1       |     at TCP.onread (net.js:597:20)                                           
```

This is all that's thrown in the application log, each multiple times.

**Comment by SISheogorath** [comment]
Can you please check the beginning of the log for sequelize-cli errors? That's the important part ^^

**Comment by almereyda** [comment]
No, there is nothing else.

**Comment by SISheogorath** [comment]
closed in favor for #894

**Pull request closed without merging**
