### PR TITLE
Integrate forkawesome with CodiMD for easier usage

### PR DESCRIPTION
**Pull request by SISheogorath**
See commit comments for details.

Basically adds `{%fa <icon name> [<color>]%}` to use the icons instead of weird `<i>` statements.

### CODE REVIEW

**Comment by ccoenen** [comment]
Is there a precedence for this syntax? I haven't seen this before.

**Comment by SISheogorath** [comment]
I took it from the [externals](https://github.com/hackmdio/codimd/blob/e0e037b5e1c30968322b0fc53274b9a9b052e593/public/docs/features.md#externals) we currently have. Wasn't sure about any other syntax that doesn't conflict with our existing integrations and possible future ones. But I'm open for suggestions.

**Comment by ccoenen** [comment]
ah, right :-)

**Comment by SISheogorath** [comment]
Thought about integrating it with the way of referencing smileys `:something:` but couldn't figure out a way to decide what is a smiley and what is an icon ^^

**Comment by SISheogorath** [comment]
@almereyda hint: Yesterday I already merged https://github.com/hackmdio/codimd/pull/1003/commits/5212bbf9c4bb14d0ee5f009512df0bb6f7a475d0 so you can already try forkAwesome icons on the demo instance. Just the further integration was put into an own PR to get forward.

**Comment by almereyda** [comment]
Please note Mermaid (https://mermaidjs.github.io/flowchart.html - at the bottom: Basic support for fontawesome) also uses a similar notation.

**Comment by SISheogorath** [comment]
@almereyda Huh, nice! may we should go for `fa:<icon name>` just seems to be a bit too easy so we could get a lot false positives :/

Any opinions on it?

**Comment by ccoenen** [comment]
`fa:<name>` will go and haunt is, in my opinion. To be more similar, one _could_ use `{%fa:<icon name>%} ` But I don't think it's a good idea to have this completely without any markup.

**Comment by ccoenen** [comment]
If someone were to write auto-complete with search for icons for this, that person would be my hero!

**Comment by SISheogorath** [comment]
Here is the list of all icons:
https://github.com/ForkAwesome/Fork-Awesome/blob/next-release/src/icons/icons.yml

Now all we need to do is taking this and make it a JSON that we can integrate during the build process ^^

**Comment by ccoenen** [comment]
this is all that's required to make this a nice simple JS object:

```js
const fs = require('fs')

const yaml = require('js-yaml')

const data = fs.readFileSync('./icons.yml')
const icons = yaml.safeLoad(data)
const sortedIcons = icons.icons.sort((a,b) => a.id.localeCompare(b.id))

const index = sortedIcons.map((i) => {
  i.filter = i.filter || []
  i.categories = i.categories || []
  i.aliases = i.aliases || []
  const ingredients = [i.name, i.id, ...i.filter, ...i.categories, ...i.aliases]
  return [i.id, ingredients.join(', ')]
})

console.log(index);
```

we're putting out an array of arrays where the first element is the id of the fork-awesome icon. Then were' mumbling up a long string of things we might want to search.

lookupHash now looks like:
```js
[
  [ '500px', '500px, 500px, Brand Icons' ],
  [ 'activitypub', 'ActivityPub, activitypub, Brand Icons' ],
  [ 'address-book', 'Address Book, address-book, Web Application Icons' ],
  [ 'address-book-o', 'Address Book Outlined, address-book-o, Web Application Icons' ],
  [ 'address-card', 'Address Card, address-card, Web Application Icons, vcard' ],
  // and so on
]
```

one could then simply search this with:

```js
const searchTerm = new RegExp('right', 'i') // yes I know /editor/i, but this might be from an input!
const result = index.filter((item) => searchTerm.test(item[1]))

console.log(result);
```

this will now output just the matching things:

```js
[
  [ 'align-right', 'align-right, align-right, text, Text Editor Icons' ],
  [ 'angle-double-right', 'Angle Double Right, angle-double-right, raquo, quote, next, forward, arrows, Directional Icons' ],
  [ 'angle-right', 'angle-right, angle-right, next, forward, arrow, Directional Icons' ],
  [ 'arrow-circle-o-right', 'Arrow Circle Outlined Right, arrow-circle-o-right, next, forward, Directional Icons' ],
  [ 'arrow-circle-right', 'Arrow Circle Right, arrow-circle-right, next, forward, Directional Icons' ],
  [ 'arrow-right', 'arrow-right, arrow-right, next, forward, Directional Icons' ],
  // and so on
]
```

**Pull request closed without merging**
