### PR TITLE
Add possibility to choose between version v3 or v4 for the gitlab api.

### LINKED ISSUE #887: Snippet import from Gitlab does not work any more
Hi all,

we authenticate CodiMD with our self-hosted Gitlab Server, which works perfectly fine. In one of our last updates of Gitlab, we noticed the "import snippet" option from CodiMD broke. We are unable to select a project where to import from.

We tried to update CodiMD, but this did not help (see the exact versions below).

CodiMD version: 1.2.0 (updated from 1.0.1-ce, installed via the docker image)
Gitlab version: 11.0.1 (Community Edition)

### PR DESCRIPTION
**Pull request by micedre**
Apart from the uri versioning, one big change is the snippet visibility post data (visibility_level -> visibility)
Should resolve #887.

Signed-off-by: Cédric Couralet <cedric.couralet@gmail.com>

### CODE REVIEW

**Comment by SISheogorath** [comment]
Nice work!

Can you please fix the linting issues?

And you should may add some code to handle invalid inputs for the gitlab API version. I can imagine some people will enter `3` instad of `v3` for what ever reason. Check the index.js in the config directory for examples and where to do :)

**Comment by micedre** [comment]
Hi,

Done (after a lot of history rewrite...), let me know what you think. I let
the default version to be v3, so no impact when updating, but this will
need to change later.

2018-07-30 18:13 GMT+02:00 Christoph (Sheogorath) Kern <
notifications@github.com>:

**Comment by SISheogorath** [comment]
:+1: looks good!

Can you may change the default value to v4 as this is what Gitlab.com uses and people probably expect this as default. (Or add a special case for Gitlab.com)

Also can you please squash your commits so we stay with a clean commit history?

As soon as these things are fixed, I'll merge it :)

**Comment by micedre** [comment]
Done, I hope I have not forgotten something.

**Comment by SISheogorath** [comment]
Thanks a lot!

**Pull request merged**
