### PR TITLE
Fix ui-edit and ui-both buttons in night mode

### LINKED ISSUE #1539: Night mode: no edit/both button highlight
When night mode is on, the "View" mode toggle is highlighted correctly (it appears slightly darker).  However the "Edit" and "Both" options do not highlight in this way.

The install appears to be using 2.1.0.

### PR DESCRIPTION
**Pull request by tamo**
Fix #1539
Active buttons should be treated equally.

### CODE REVIEW

**Comment by Yukaii** [comment]
Hi @tamo thanks for the contribution, please sign off your commit:

https://github.com/hackmdio/codimd/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by Yukaii** [comment]
@tamo Every commit should be signed off, you could use `git rebase --signoff` command

**Comment by tamo** [comment]
Rebased. Let me know if I have to do more.

**Review by Yukaii — APPROVED** [review]

**Comment by Yukaii** [comment]
@tamo This PR should be merged into `develop` branch. Please rebase against develop branch.

**Comment by tamo** [comment]
I did the following:
```
git rebase --onto origin/develop origin/master patch-1
git push -f
```
I'm not sure I did it correctly

**Comment by Yukaii** [comment]
@tamo That's correct, thank you for the contribution 💯

**Pull request merged**
