### PR TITLE
Fix/naming

### LINKED ISSUE #1219: Naming
Currently, there are two active repositories/softwares named "CodiMD": This one and [codimd/server](https://github.com/codimd/server). Both are actively maintained, but by different people. Especially for someone new to CodiMD/HackMD it's almost impossible to understand what's what.

As I understand, this repo is now maintained by you, the HackMD people, and you want to use it as open-core-model within HackMD Enterprise. The people who maintained this repo beforehand, who did the initial renaming to "CodiMD", are now at codimd/server.

What are your plans regarding the naming situation? I'd propose to rename this to HackMD Community Edition, because it's the conventional naming scheme for open-core-models, and it would make it far easier to understand that codimd/server is seperate and maintained by the people who created the name, and this and HackMD EE belong together and are maintained by the same people.

### PR DESCRIPTION
**Pull request by dragetd**
Fixes #1219

We probably should bump the version to reflect this change, as it requires existing configs to be updated.

I also fixed the environment variables to reflect the change. This needs some testing. Once we agree on the version and have things tested, this PR is no longer WIP. :)

### CODE REVIEW

**Comment by dragetd** [comment]
Rebased the PR onto most recent develop. Updated the screenshots to show the right name.

**Comment by dragetd** [comment]
Rebased on current develop.

**Comment by dragetd** [comment]
Did anyone check why travis was failing?

**Comment by dragetd** [comment]
I am trying to take a step towards the project here and help out with the suggested name-hange as discussed in #1219 . I took the effort to also edit screenshots and check/fix URLs.

I'd really appreciate at least *some* sort of feedback to #1219 and how to progress from here.

**Comment by dragetd** [comment]
Any news on this side or #1219 ?

**Comment by dragetd** [comment]
*knock knock*, is this thing even on?

**Comment by jackycute** [comment]
Hi @dragetd,
Thanks for pull request.
We have no plan to change the name at the moment.

**Pull request closed without merging**
